name: Lint

on:
  pull_request:
    paths:
      - "**.py"
  push:
    paths:
      - "**.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install pylint
      - run: pip install -r requirements.txt
      - run: pylint --recursive=y . --rcfile .pylintrc